### PR TITLE
Add allow_blank option

### PR DESCRIPTION
**Pull request by cmckni3**
Adds an allow_blank option for the validator. Allows phone number to be blank and skip validation

### CODE REVIEW

**Comment by travisjeffery** [comment]
Thanks, I actually call `#blank?` though rather than `#empty?` and wrote a test. Just shipped 2.0.1.

**Comment by cmckni3** [comment]
Oops. Yeah that's actually a better idea

**Comment by cmckni3** [comment]
Hmm. Did this actually break the validator? I can't get ten or seven digit phone numbers to pass validation

**Comment by travisjeffery** [comment]
The tests all pass.

``` ruby
  def test_validates_ten_or_seven_digit_number
    Person.validates :phone_number, :phone_number => {:ten_digits => true, :seven_digits => true}
    @person.phone_number = "555-5555"
    assert @person.valid?
    @person.phone_number = "555.555.5555"
    assert @person.valid?
  end
```

This works.

**Comment by cmckni3** [comment]
It seems to fail validations when the allow_blank option is specified. I'm tinkering with the tests on my fork

**Comment by cmckni3** [comment]
I just made this test case in my fork and it fails

``` ruby
    def test_validates_phone_number_with_allow_blank
      Person.validates :phone_number, :phone_number => {:allow_blank => true}

      @person.phone_number = "555-565-5703"
      assert @person.valid?

      @person.phone_number = "565-5703"
      assert @person.valid?
    end
```

**Comment by travisjeffery** [comment]
I'm on my phone right now and haven't tested this but I'm pretty sure you should just have to pass :ten_digits, :seven_digits along with :allow_blank.

**Comment by cmckni3** [comment]
Let me try that

**Comment by cmckni3** [comment]
Sweet that works. Thanks

**Comment by travisjeffery** [comment]
Yep, np.

**Pull request closed without merging**
